package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sample.model.BulletinBoardData;
import sample.model.BulletinBoardDataExample;

public interface BulletinBoardDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int countByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int deleteByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int insert(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int insertSelective(BulletinBoardData record);


    /**
     * データ登録
     *
     * ※idを自動採番する
     *
     * @param record
     * @return　
     */
    int insertBulletinBoardDataAutoNumbering(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    List<BulletinBoardData> selectByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int updateByExampleSelective(@Param("record") BulletinBoardData record, @Param("example") BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int updateByExample(@Param("record") BulletinBoardData record, @Param("example") BulletinBoardDataExample example);
}