package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sample.model.BulletinBoardData;
import sample.model.BulletinBoardDataExample;

public interface BulletinBoardDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int countByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int deleteByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int insert(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int insertSelective(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    List<BulletinBoardData> selectByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int updateByExampleSelective(@Param("record") BulletinBoardData record, @Param("example") BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Mon Oct 26 17:23:44 JST 2015
     */
    int updateByExample(@Param("record") BulletinBoardData record, @Param("example") BulletinBoardDataExample example);

    // *****************************
    // 追加で作成した処理
    // *****************************
    /**
     * idのMax値を取得して返却する
     *
     * @param example
     * @return idのMax値
     */
    Integer selectByIdMax();

    /**
     * 指定した名前に該当するデータを検索する
     *
     * @param name 名前
     * @return 該当データ(リスト)
     */
    List<BulletinBoardData> selectByName(String name);
}