package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sample.model.BulletinBoardData;
import sample.model.BulletinBoardDataExample;

public interface BulletinBoardDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int countByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int deleteByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int insert(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int insertSelective(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    List<BulletinBoardData> selectByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    BulletinBoardData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByExampleSelective(@Param("record") BulletinBoardData record, @Param("example") BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByExample(@Param("record") BulletinBoardData record, @Param("example") BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByPrimaryKeySelective(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_board_data
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByPrimaryKey(BulletinBoardData record);
}