package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sample.model.SystemProperty;
import sample.model.SystemPropertyExample;

public interface SystemPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int countByExample(SystemPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int deleteByExample(SystemPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int deleteByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int insert(SystemProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int insertSelective(SystemProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    List<SystemProperty> selectByExample(SystemPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    SystemProperty selectByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByExampleSelective(@Param("record") SystemProperty record, @Param("example") SystemPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByExample(@Param("record") SystemProperty record, @Param("example") SystemPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByPrimaryKeySelective(SystemProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_property
     *
     * @mbggenerated Fri Nov 13 14:46:54 JST 2015
     */
    int updateByPrimaryKey(SystemProperty record);
}