package sample.mapper;

import java.util.List;
import sample.model.SystemProperty;
import sample.model.SystemPropertyExample;
import sample.model.SystemPropertyKey;

public interface SystemPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_property
     *
     * @mbggenerated Tue Nov 24 04:11:13 JST 2015
     */
    int deleteByPrimaryKey(SystemPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_property
     *
     * @mbggenerated Tue Nov 24 04:11:13 JST 2015
     */
    int insert(SystemProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_property
     *
     * @mbggenerated Tue Nov 24 04:11:13 JST 2015
     */
    int insertSelective(SystemProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_property
     *
     * @mbggenerated Tue Nov 24 04:11:13 JST 2015
     */
    List<SystemProperty> selectByExample(SystemPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_property
     *
     * @mbggenerated Tue Nov 24 04:11:13 JST 2015
     */
    SystemProperty selectByPrimaryKey(SystemPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_property
     *
     * @mbggenerated Tue Nov 24 04:11:13 JST 2015
     */
    int updateByPrimaryKeySelective(SystemProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.system_property
     *
     * @mbggenerated Tue Nov 24 04:11:13 JST 2015
     */
    int updateByPrimaryKey(SystemProperty record);
}