package sample.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sample.model.UserRolesExample;
import sample.model.UserRolesKey;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    int countByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    int deleteByPrimaryKey(UserRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    int insert(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    int insertSelective(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    List<UserRolesKey> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    int updateByExampleSelective(@Param("record") UserRolesKey record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbggenerated Fri Nov 06 14:00:45 JST 2015
     */
    int updateByExample(@Param("record") UserRolesKey record, @Param("example") UserRolesExample example);
}