package sample.mapper;

import java.util.List;
import sample.model.UserRolesExample;
import sample.model.UserRolesKey;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    int deleteByPrimaryKey(UserRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    int insert(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    int insertSelective(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    List<UserRolesKey> selectByExample(UserRolesExample example);
}