package sample.model;

public class UserInfo extends UserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.password
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.organization_name
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    private String organizationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.enabled
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.password
     *
     * @return the value of public.user_info.password
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.password
     *
     * @param password the value for public.user_info.password
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.organization_name
     *
     * @return the value of public.user_info.organization_name
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.organization_name
     *
     * @param organizationName the value for public.user_info.organization_name
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.enabled
     *
     * @return the value of public.user_info.enabled
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.enabled
     *
     * @param enabled the value for public.user_info.enabled
     *
     * @mbggenerated Fri Nov 20 22:39:06 JST 2015
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}